stages:
    - Build
    - PipelineSAST-AgentSCA
    - PolicySAST

Compile Application:
    image: maven:3.6.0-jdk-8
    stage: Build
    script:
      - mvn clean package
    artifacts:
      name: verademo-gitlab
      paths:
        - target/
      expire_in: 5 week
    cache:
      paths:
        - target/
        - .m2/repository

Pipeline Scan Staic Analysis:
    image: veracode/pipeline-scan:latest
    stage: PipelineSAST-AgentSCA
    except:
      refs:
        - schedules
      changes:
        - pipeline-basline.json
    script:
        - java -jar /opt/veracode/pipeline-scan.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_KEY} -f /target/verademo.war
    allow_failure: true