stages:
    - Build
    - PipelineSAST-AgentSCA
    - PolicySAST

Compile Application:
    image: maven:3.6.0-jdk-8
    stage: Build
    script:
      - mvn clean package
    artifacts:
      name: verademo-gitlab
      paths:
        - target/
      expire_in: 5 week
    cache:
      paths:
        - target/
        - .m2/repository

pipeline_scan:
    image: veracode/pipeline-scan:latest
    stage: PipelineSAST-AgentSCA
    script:
        - java -jar pipeline-scan.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_KEY} --file target/verademo.war
    artifacts:
        paths:
            - pipelinescanresults.json
    allow_failure: true